repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.16.3
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: flake8
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
      - id: isort
        exclude: '^demo\.py$'
